version: "3"
services:
    server:
        build: ./
        image: mohamedazab/switchspace:latest
        container_name: "switchspace-server"
        depends_on:
            - "mongodb"
        environment:
            - MONGODB_URI=mongodb://mongodb:27017/switchspace
        ports:
            - "3000:3000"
        restart: always
    mongodb:
        image: mongo:latest
        container_name: "switch-space-database"
        environment:
            - MONGO_DATA_DIR=/data/db
        # volumes:
        # - ./data/:/data/db
        ports:
            - "27017:27017"
